# Generated by Django 4.0 on 2024-02-19 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cargo', models.CharField(max_length=200)),
                ('departure_time', models.DateField()),
                ('arrival_time', models.DateField()),
                ('origin', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('max_weight', models.IntegerField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='transport_images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('transport_type', models.CharField(choices=[('Фура', 'Фура'), ('Автосцепка', 'Автосцепка'), ('Автоцистерна', 'Автоцистерна'), ('Открытая платформа', 'Открытая платформа')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150)),
                ('number_phone', models.CharField(max_length=30)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freight_linker_app.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150)),
                ('number_phone', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Занят', 'Занят'), ('Ожидаю груз', 'Ожидаю груз'), ('Пустой', 'Пустой')], max_length=50)),
                ('about_me', models.TextField(blank=True, max_length=200, null=True)),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freight_linker_app.transport')),
            ],
        ),
    ]
