# Generated by Django 4.0 on 2024-02-20 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freight_linker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_driver',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freight_linker_app.users'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freight_linker_app.users'),
        ),
    ]
