# Generated by Django 4.0 on 2024-02-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight_linker_app', '0003_profile_driver_destination_profile_driver_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('Водитель', 'Водитель'), ('Отправитель', 'Отправитель')], max_length=50, null=True),
        ),
    ]
