# Generated by Django 4.0 on 2024-02-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freight_linker_app', '0005_remove_transport_image_remove_transport_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='cargo',
        ),
        migrations.AddField(
            model_name='cargo',
            name='profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freight_linker_app.user_profile'),
        ),
    ]
